<script setup lang="ts">
import { onMounted,ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
type User={id:number;username:string;quota_gb:number;expires_at:string}
const {t}=useI18n(),router=useRouter(),users=ref<User[]>([]),loading=ref(false),error=ref(''),name=ref(''),quota=ref(50),expiry=ref('')
const headers=()=>({Authorization:'Bearer '+(localStorage.getItem('token')||''),'Content-Type':'application/json'})
async function load(){loading.value=true;error.value='';try{const r=await fetch('/api/users',{headers:headers()});if(!r.ok)throw Error(t('dashboard.loadError'));users.value=await r.json()}catch(e){error.value=e instanceof Error?e.message:String(e)}finally{loading.value=false}}
async function add(){try{const r=await fetch('/api/users',{method:'POST',headers:headers(),body:JSON.stringify({username:name.value,quota_gb:quota.value,expires_at:expiry.value})});if(!r.ok)throw Error(t('dashboard.addError'));name.value='';await load()}catch(e){error.value=e instanceof Error?e.message:String(e)}}
function logout(){localStorage.removeItem('token');router.push('/login')}
onMounted(load)
</script>
<template><section class="dashboard"><div class="dash-head"><div><p class="eyebrow">CONTROL CENTER</p><h1>{{t('dashboard.title')}}</h1><p class="muted">{{t('dashboard.subtitle')}}</p></div><button class="ghost" @click="logout">{{t('dashboard.logout')}} ↗</button></div><div class="glass stats"><div><span class="muted">{{t('dashboard.total')}}</span><strong>{{users.length}}</strong></div><div><span class="muted">{{t('dashboard.status')}}</span><strong class="live">● {{t('dashboard.ready')}}</strong></div></div><form class="glass add-form" @submit.prevent="add"><h2>{{t('dashboard.add')}}</h2><input v-model.trim="name" :placeholder="t('dashboard.username')" required maxlength="64"><input v-model.number="quota" type="number" min="1" max="100000" :placeholder="t('dashboard.quota')" required><input v-model="expiry" type="date" required><button class="primary">{{t('dashboard.create')}} +</button></form><p v-if="error" class="error">{{error}}</p><div class="glass table-wrap"><div class="table-title"><h2>{{t('dashboard.users')}}</h2><button class="ghost" @click="load">{{t('dashboard.refresh')}} ↻</button></div><p v-if="loading" class="muted">{{t('dashboard.loading')}}</p><p v-else-if="!users.length" class="muted">{{t('dashboard.empty')}}</p><div v-else class="user-list"><div v-for="u in users" :key="u.id" class="user-row"><div class="avatar">{{u.username.slice(0,1).toUpperCase()}}</div><div class="user-info"><b>{{u.username}}</b><small>{{u.quota_gb}} GB · {{u.expires_at?.slice(0,10)}}</small></div><span class="pill">{{t('dashboard.created')}}</span></div></div></div><p class="hint">{{t('dashboard.disclaimer')}}</p></section></template>